/*
 Navicat Premium Data Transfer

 Source Server         : hospital management
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Schema         : C##HOSPITAL_MANAGEMENT_DB

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 25/02/2022 17:31:09
*/


-- ----------------------------
-- Table structure for ADMITTED_PATIENT
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."ADMITTED_PATIENT";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."ADMITTED_PATIENT" (
  "PATIENT_ID" VARCHAR2(50 BYTE) VISIBLE,
  "DOCTOR_ID" VARCHAR2(50 BYTE) VISIBLE,
  "ADMITTED_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "RELEASE_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "WARD_NO" VARCHAR2(50 BYTE) VISIBLE,
  "BED_NO" VARCHAR2(50 BYTE) VISIBLE,
  "ADMITTED_ID" NUMBER VISIBLE DEFAULT "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81502".nextval NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ADMITTED_PATIENT
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."ADMITTED_PATIENT" VALUES ('shafaet', 'kabir', '2022-02-23', '2022/02/23 10:24:44', 'w-1', 'b-1', '41');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."ADMITTED_PATIENT" VALUES ('shafaet', 'kabir', '2022-02-24', '2022/02/23 23:35:21', 'w-1', 'b-3', '61');

-- ----------------------------
-- Table structure for APPOINTMENTS
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" (
  "STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "APPOINTMENT_ID" NUMBER VISIBLE DEFAULT "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_78255".nextval NOT NULL,
  "SCHEDULE_ID" NUMBER VISIBLE,
  "APPOINTMENT_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "PATIENT_ID" VARCHAR2(50 BYTE) VISIBLE,
  "DOCTOR_ID" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of APPOINTMENTS
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" VALUES ('visited', '61', '89', '2022/02/23 10:04:38', 'shafaet', 'kabir');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" VALUES ('visited', '62', '81', '2022/02/23 10:46:18', 'shafaet', 'kabir');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" VALUES ('visited', '63', '89', '2022/02/23 11:41:26', 'shafaet', 'kabir');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" VALUES ('visited', '64', '89', '2022/02/23 11:41:45', 'shafaet', 'kabir');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" VALUES ('visited', '81', '89', '2022/02/23 23:29:13', 'shafaet', 'kabir');

-- ----------------------------
-- Table structure for BED
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."BED";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."BED" (
  "BED_NO" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "WARD_NO" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of BED
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BED" VALUES ('b-3', 'w-1');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BED" VALUES ('b-4', 'w-2');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BED" VALUES ('b-5', 'w-2');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BED" VALUES ('b-6', 'w-2');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BED" VALUES ('b-11', 'w-3');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BED" VALUES ('b-1', 'w-1');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BED" VALUES ('b-2', 'w-1');

-- ----------------------------
-- Table structure for BILL
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."BILL";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."BILL" (
  "BILL_ID" NUMBER VISIBLE DEFAULT "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81872".nextval NOT NULL,
  "BILL_TYPE" VARCHAR2(50 BYTE) VISIBLE,
  "BILL_CREATE_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "BILL_CLEAR_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "BILL_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "PATIENT_ID" VARCHAR2(50 BYTE) VISIBLE,
  "AMOUNT" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of BILL
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('62', 'TEST', '2022-02-23', '2022/02/23 10:16:05', 'clear', 'shafaet', '5000');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('63', 'OPERATION', '2022-02-23', '2022/02/23 10:26:10', 'clear', 'shafaet', '250000');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('61', 'APPOINTMENT', '2022-02-23', '2022/02/23 10:05:31', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('64', 'APPOINTMENT', '2022-02-23', '2022/02/23 11:42:52', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('65', 'APPOINTMENT', '2022-02-23', '2022/02/23 22:55:15', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('66', 'APPOINTMENT', '2022-02-23', '2022/02/23 22:55:16', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('67', 'APPOINTMENT', '2022-02-23', '2022/02/23 22:55:17', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('68', 'APPOINTMENT', '2022-02-23', '2022/02/23 22:55:18', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('69', 'APPOINTMENT', '2022-02-23', '2022/02/23 22:55:19', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('83', 'APPOINTMENT', '2022-02-23', '2022/02/23 22:55:19', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('81', 'APPOINTMENT', '2022-02-23', '2022/02/23 22:55:20', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('82', 'APPOINTMENT', '2022-02-23', '2022/02/23 22:55:20', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('84', 'APPOINTMENT', '2022-02-23', '2022/02/23 23:29:46', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('85', 'APPOINTMENT', '2022-02-23', '2022/02/23 23:32:05', 'clear', 'shafaet', '1500');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('86', 'TEST', '2022-02-23', '2022/02/23 23:32:08', 'clear', 'shafaet', '10000');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."BILL" VALUES ('87', 'OPERATION', '2022-02-23', '2022/02/23 23:33:28', 'clear', 'shafaet', '250000');

-- ----------------------------
-- Table structure for DEPARTMENT
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" (
  "DEPARTMENT_NAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "AVERAGE_SALARY" NUMBER VISIBLE,
  "ID" NUMBER VISIBLE DEFAULT "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_78224".nextval NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DEPARTMENT
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" VALUES ('Cardiologist', '150000', '41');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" VALUES ('Audiologist', '150000', '42');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" VALUES ('Dentist', '150000', '43');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" VALUES ('ENT specialist', '150000', '44');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" VALUES ('Orthopaedic surgeon', '150000', '45');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" VALUES ('Paediatrician', '150000', '46');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" VALUES ('Psychiatrists', '150000', '47');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" VALUES ('Neurologist', '150000', '48');

-- ----------------------------
-- Table structure for DOCTORS
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" (
  "ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "PHONE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "ADDRESS" VARCHAR2(50 BYTE) VISIBLE,
  "FIRST_NAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "LAST_NAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE,
  "DEPARTMENT_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "GENDER" VARCHAR2(15 BYTE) VISIBLE,
  "DESIGNATION" VARCHAR2(50 BYTE) VISIBLE,
  "QUALIFICATION" VARCHAR2(50 BYTE) VISIBLE,
  "VISITING_FEE" NUMBER VISIBLE,
  "DATE_OF_BIRTH" VARCHAR2(30 BYTE) VISIBLE,
  "CHAMBER" VARCHAR2(20 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DOCTORS
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" VALUES ('kabir', '0123456789', 'Jessore, Bangladesh', 'Dr Musa', 'Kabir', 'kabir@gmail.com', 'ENT specialist', 'Male', 'specialist', 'MBBS, MMSc', '1500', '01-JAN-90', '1002');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" VALUES ('shamim', '0123456789', 'Kushtia, Bangladesh', 'Dr Asaduzzaman', 'Shamim', 'shamim@gmail.com', 'Cardiologist', 'Male', 'specialist', 'MBBS, MMSc', '2000', '01-JAN-85', '1001');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" VALUES ('ashraful', '0123456789', 'Kushtia, Bangladesh', 'Dr Ashraful', 'Haque', 'ashraful@gmail.com', 'Neurologist', 'Male', 'specialist', 'MBBS, MMSc', '2500', '01-JAN-80', '1003');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" VALUES ('salek', '0123456789', 'Kushtia, Bangladesh', 'Dr Salek', 'Masud', 'salek@gmail.com', 'Audiologist', 'Male', 'Senior_resident', 'MBBS, MMSc', '2000', '01-JAN-88', '1004');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" VALUES ('iftekhar', '0123456789', 'Kushtia, Bangladesh', 'Dr Iftekhar', 'Mahmud', 'iftekhar@gmail.com', 'Cardiologist', 'Male', 'Head_of_department', 'MBBS, MMSc', '2500', '01-JAN-90', '1009');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" VALUES ('jahangir', '0123456789', 'Dhaka, Bangladesh', 'Dr Jahangir', 'Kabir', 'jahangir@gmail.com', 'Cardiologist', 'Male', 'Head_of_department', 'MBBS, MMSc', '3500', '01-JAN-90', '1010');

-- ----------------------------
-- Table structure for DOCTOR_SCHEDULE
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" (
  "DOCTOR_ID" VARCHAR2(15 BYTE) VISIBLE,
  "SCHEDULE_DATE" VARCHAR2(20 BYTE) VISIBLE,
  "START_TIME" VARCHAR2(20 BYTE) VISIBLE,
  "END_TIME" VARCHAR2(20 BYTE) VISIBLE,
  "PLACE" VARCHAR2(20 BYTE) VISIBLE,
  "ID" NUMBER VISIBLE DEFAULT "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_80594".nextval NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DOCTOR_SCHEDULE
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('kabir', '2022-02-24', '19:00', '21:00', 'Chamber', '89');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('kabir', '2022-02-23', '13:40', '13:40', 'Chamber', '90');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('kabir', '2022-02-23', '22:00', '23:00', 'Ward', '83');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('shamim', '2022-02-23', '15:00', '16:30', 'Chamber', '84');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('shamim', '2022-02-23', '17:00', '19:00', 'Operation_Theatre', '85');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('shamim', '2022-02-23', '22:00', '23:00', 'Ward', '86');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('kabir', '2022-02-23', '15:00', '17:00', 'Chamber', '81');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('kabir', '2022-02-23', '19:30', '21:00', 'Operation_Theatre', '82');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('ashraful', '2022-02-23', '16:45', '19:00', 'Chamber', '87');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" VALUES ('salek', '2022-02-23', '21:15', '23:15', 'Chamber', '88');

-- ----------------------------
-- Table structure for EMPLOYEE_SCHEDULE
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."EMPLOYEE_SCHEDULE";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."EMPLOYEE_SCHEDULE" (
  "ID" NUMBER VISIBLE DEFAULT "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81284".nextval NOT NULL,
  "EMPLOYEE_ID" VARCHAR2(50 BYTE) VISIBLE,
  "DAY" VARCHAR2(50 BYTE) VISIBLE,
  "START_TIME" VARCHAR2(50 BYTE) VISIBLE,
  "END_TIME" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of EMPLOYEE_SCHEDULE
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."EMPLOYEE_SCHEDULE" VALUES ('61', 'riyadh', 'sunday', '09:00', '17:00');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."EMPLOYEE_SCHEDULE" VALUES ('41', 'tashin', 'saturday', '09:00', '17:00');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."EMPLOYEE_SCHEDULE" VALUES ('42', 'tashin', 'sunday', '21:00', '17:00');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."EMPLOYEE_SCHEDULE" VALUES ('63', 'riyadh', 'wednesday', '02:00', '20:57');

-- ----------------------------
-- Table structure for OPERATION
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."OPERATION";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."OPERATION" (
  "ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "OPERATION_NAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "COST" NUMBER VISIBLE,
  "ROOM_NO" VARCHAR2(10 BYTE) VISIBLE,
  "STATUS" VARCHAR2(25 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of OPERATION
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."OPERATION" VALUES ('o-heart-valve', 'Heart Valve Repair', '250000', '2003', 'available');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."OPERATION" VALUES ('o-heart-bypass', 'Heart Bypass Surgery', '250000', '2001', 'available');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."OPERATION" VALUES ('o-pacemaker', 'Pacemakers', '250000', '2008', 'available');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."OPERATION" VALUES ('gastric', 'gastric bypass', '20000', '3009', 'available');

-- ----------------------------
-- Table structure for PATIENTS
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENTS";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENTS" (
  "ID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "PHONE_NO" VARCHAR2(50 BYTE) VISIBLE,
  "ADDRESS" VARCHAR2(50 BYTE) VISIBLE,
  "FIRST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "DATE_OF_BIRTH" VARCHAR2(50 BYTE) VISIBLE,
  "GENDER" VARCHAR2(50 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PATIENTS
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PATIENTS" VALUES ('rakib', '0123456789', 'Kushtia', 'Abdur', 'Rakib', '1995-01-01', 'Male', 'rakib@gmail.com');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PATIENTS" VALUES ('shafaet', '0123456789', 'Kushtia, Bangladesh', 'Shafaet', 'Islam', '2000-01-01', 'Male', 'shafaet@gmail.com');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PATIENTS" VALUES ('azmol', '0123456789', 'Kushtia, Bangladesh', 'Md Azmol', 'Hossain', '1995-01-01', 'Male', 'azmol@gmail.com');

-- ----------------------------
-- Table structure for PATIENT_OPERATION
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_OPERATION";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_OPERATION" (
  "OPERATION_ID" VARCHAR2(50 BYTE) VISIBLE,
  "DOCTOR_ID" VARCHAR2(50 BYTE) VISIBLE,
  "PATIENT_ID" VARCHAR2(50 BYTE) VISIBLE,
  "OPERATION_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "OPERATION_TIME" VARCHAR2(50 BYTE) VISIBLE,
  "RESULT" VARCHAR2(50 BYTE) VISIBLE,
  "OPERATION_NO" NUMBER VISIBLE DEFAULT "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81475".nextval NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PATIENT_OPERATION
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_OPERATION" VALUES ('o-pacemaker', 'kabir', 'shafaet', '2022-02-23', '13:27', 'successfull', '61');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_OPERATION" VALUES ('o-pacemaker', 'kabir', 'shafaet', '2022-02-24', '23:35', 'successfull', '81');

-- ----------------------------
-- Table structure for PATIENT_TEST
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_TEST";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_TEST" (
  "TEST_ID" VARCHAR2(15 BYTE) VISIBLE,
  "TEST_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "RESULT" VARCHAR2(50 BYTE) VISIBLE,
  "SAMPLE_NO" NUMBER VISIBLE DEFAULT "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81472".nextval NOT NULL,
  "RESULT_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "PATIENT_ID" VARCHAR2(50 BYTE) VISIBLE,
  "DOCTOR_ID" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PATIENT_TEST
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_TEST" VALUES ('t-albumin', '2022-02-23', 'all okey', '61', '2022/02/23 10:15:49', 'shafaet', 'kabir');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_TEST" VALUES ('cbc', '2022-02-23', 'all okey', '81', '2022/02/23 23:32:41', 'shafaet', 'kabir');

-- ----------------------------
-- Table structure for PRESCRIPTION
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION" (
  "APPOINTMENT_ID" NUMBER VISIBLE NOT NULL,
  "PROBLEM" VARCHAR2(100 BYTE) VISIBLE,
  "MEDICINE" VARCHAR2(100 BYTE) VISIBLE,
  "TEST" VARCHAR2(100 BYTE) VISIBLE,
  "OPERATION" VARCHAR2(100 BYTE) VISIBLE,
  "OTHERS" VARCHAR2(100 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PRESCRIPTION
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION" VALUES ('61', 'heart infection', 'indever', 'Albumin Blood Test', 'Pacemakers', NULL);
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION" VALUES ('62', 'heart disease', 'indever', 'antibody test', 'pacemaker', 'keep rest 2 weeks');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION" VALUES ('81', 'pain in heart', 'indever', 'complete blood count', 'gastric bypass', 'take rest');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION" VALUES ('63', 'something', 'some medicine', 'some test', 'some operation', 'others');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION" VALUES ('64', NULL, NULL, NULL, NULL, NULL);

-- ----------------------------
-- Table structure for RECEPTIONIST
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."RECEPTIONIST";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."RECEPTIONIST" (
  "ID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "PHONE_NO" VARCHAR2(50 BYTE) VISIBLE,
  "ADDRESS" VARCHAR2(50 BYTE) VISIBLE,
  "FIRST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "DATE_OF_BIRTH" VARCHAR2(50 BYTE) VISIBLE,
  "GENDER" VARCHAR2(50 BYTE) VISIBLE,
  "DESIGNATION" VARCHAR2(50 BYTE) VISIBLE,
  "QUALIFICATION" VARCHAR2(50 BYTE) VISIBLE,
  "SALARY" NUMBER VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of RECEPTIONIST
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."RECEPTIONIST" VALUES ('tashin', '0123456789', 'Kushtia, Bangladesh', 'Tashin', 'Ahmed', '1995-01-01', 'Male', 'Junior', 'BA', '25000', 'tashin@gmail.com');

-- ----------------------------
-- Table structure for TECHNICIANS
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."TECHNICIANS";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."TECHNICIANS" (
  "ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "PHONE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "ADDRESS" VARCHAR2(50 BYTE) VISIBLE,
  "FIRST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "DATE_OF_BIRTH" VARCHAR2(50 BYTE) VISIBLE,
  "GENDER" VARCHAR2(50 BYTE) VISIBLE,
  "DESIGNATION" VARCHAR2(50 BYTE) VISIBLE,
  "QUALIFICATION" VARCHAR2(50 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE,
  "SALARY" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of TECHNICIANS
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."TECHNICIANS" VALUES ('alamin', '0123456789', 'Rangpur, Bangladesh', 'Alamin', 'Hossain', '2000-01-01', 'Male', 'Intern', 'BSC', 'alamin@gmail.com', '15000');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."TECHNICIANS" VALUES ('riyadh', '0123456789', 'Kushtia, Bangladesh', 'Riyadh', 'Rahman', '2000-01-01', 'Male', 'Junior', 'BSC', 'riyadh@gmail.com', '30000');

-- ----------------------------
-- Table structure for TEST
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."TEST";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."TEST" (
  "ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "TEST_NAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "ROOM_NO" VARCHAR2(15 BYTE) VISIBLE,
  "TECHNITIAN_ID" VARCHAR2(15 BYTE) VISIBLE,
  "COST" NUMBER VISIBLE,
  "STATUS" VARCHAR2(25 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of TEST
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."TEST" VALUES ('t-albumin', 'Albumin Blood Test', '1005', 'riyadh', '5000', 'available');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."TEST" VALUES ('t-glucose', 'Blood Glucose Test', '1006', 'riyadh', '5000', 'available');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."TEST" VALUES ('t-antibody', 'CCP Antibody Test', '1006', 'riyadh', '4000', 'available');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."TEST" VALUES ('t-blood_type', 'blood type test', '2006', 'riyadh', '10000', 'unavailable');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."TEST" VALUES ('cbc', 'complete blood count', '2008', 'riyadh', '10000', 'available');

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERS";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERS" (
  "ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "USER_TYPE_ID" VARCHAR2(2 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('admin', 'admin', '0');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('rakib', 'rakib', '2');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('ashraful', 'ashraful', '1');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('salek', 'salek', '1');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('shamim', 'shamim', '1');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('kabir', 'kabir', '1');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('tashin', 'tashin', '4');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('alamin', 'alamin', '3');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('riyadh', 'riyadh', '3');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('shafaet', 'shafaet', '2');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('azmol', 'azmol', '2');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('iftekhar', 'iftekhar', '1');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERS" VALUES ('jahangir', 'jahangir', '1');

-- ----------------------------
-- Table structure for USERTYPE
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" (
  "ID" VARCHAR2(2 BYTE) VISIBLE NOT NULL,
  "TYPENAME" VARCHAR2(15 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERTYPE
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" VALUES ('0', 'ADMIN');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" VALUES ('4', 'RECEIPTIONIST');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" VALUES ('1', 'DOCTOR');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" VALUES ('2', 'PATIENT');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" VALUES ('3', 'TECHNITIAN');

-- ----------------------------
-- Table structure for WARD
-- ----------------------------
DROP TABLE "C##HOSPITAL_MANAGEMENT_DB"."WARD";
CREATE TABLE "C##HOSPITAL_MANAGEMENT_DB"."WARD" (
  "WARD_NO" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "WARD_TYPE" VARCHAR2(50 BYTE) VISIBLE,
  "COST_PER_BED" NUMBER VISIBLE,
  "ROOM_NO" VARCHAR2(20 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of WARD
-- ----------------------------
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."WARD" VALUES ('w-1', 'GENERAL_WARD', '1000', '3001');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."WARD" VALUES ('w-2', 'SEMI-SPECIAL_ROOM', '2000', '3003');
INSERT INTO "C##HOSPITAL_MANAGEMENT_DB"."WARD" VALUES ('w-3', 'ICCU', '1000', '3010');

-- ----------------------------
-- Sequence structure for ISEQ$$_78224
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_78224";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_78224" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78255
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_78255";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_78255" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_80594
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_80594";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_80594" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_81284
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81284";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81284" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_81472
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81472";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81472" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_81473
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81473";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81473" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_81475
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81475";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81475" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_81502
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81502";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81502" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_81872
-- ----------------------------
DROP SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81872";
CREATE SEQUENCE "C##HOSPITAL_MANAGEMENT_DB"."ISEQ$$_81872" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table ADMITTED_PATIENT
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."ADMITTED_PATIENT" ADD CONSTRAINT "PK_ADMITTED_PATIENT" PRIMARY KEY ("ADMITTED_ID");

-- ----------------------------
-- Checks structure for table ADMITTED_PATIENT
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."ADMITTED_PATIENT" ADD CONSTRAINT "SYS_C008246" CHECK ("ADMITTED_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table APPOINTMENTS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" ADD CONSTRAINT "PK_APPOINTMENT" PRIMARY KEY ("APPOINTMENT_ID");

-- ----------------------------
-- Checks structure for table APPOINTMENTS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" ADD CONSTRAINT "SYS_C008227" CHECK ("APPOINTMENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table APPOINTMENTS
-- ----------------------------
CREATE TRIGGER "C##HOSPITAL_MANAGEMENT_DB"."ADD_BILL_AFTER_APPOINTMENTS_APPROVED" AFTER UPDATE OF "STATUS" ON "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE
	V_BILL_TYPE VARCHAR2(50);
	V_BILL_CREATE_DATE VARCHAR2(50);
	V_BILL_STATUS VARCHAR2(50);
	V_PATIENT_ID VARCHAR2(50);
	V_AMOUNT NUMBER;
BEGIN
	V_BILL_TYPE:='APPOINTMENT';
	V_BILL_CREATE_DATE:=TO_CHAR( SYSDATE, 'YYYY-MM-DD' );
	V_BILL_STATUS:='DUE';
	V_PATIENT_ID:=:NEW.PATIENT_ID;
	SELECT VISITING_FEE INTO V_AMOUNT 
	FROM DOCTORS WHERE ID=:NEW.DOCTOR_ID;
	INSERT INTO BILL(BILL_TYPE,BILL_CREATE_DATE,BILL_STATUS,
	PATIENT_ID,AMOUNT) VALUES(V_BILL_TYPE,V_BILL_CREATE_DATE,
	V_BILL_STATUS,V_PATIENT_ID,V_AMOUNT);
END;
/

-- ----------------------------
-- Primary Key structure for table BED
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."BED" ADD CONSTRAINT "PK_BED" PRIMARY KEY ("BED_NO");

-- ----------------------------
-- Checks structure for table BILL
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."BILL" ADD CONSTRAINT "SYS_C008247" CHECK ("BILL_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table DEPARTMENT
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" ADD CONSTRAINT "SYS_C007918" CHECK ("DEPARTMENT_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."DEPARTMENT" ADD CONSTRAINT "SYS_C008254" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DOCTORS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" ADD CONSTRAINT "DOCTORS_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table DOCTORS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" ADD CONSTRAINT "SYS_C008165" CHECK ("FIRST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" ADD CONSTRAINT "SYS_C008166" CHECK ("LAST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table DOCTOR_SCHEDULE
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTOR_SCHEDULE" ADD CONSTRAINT "SYS_C008175" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EMPLOYEE_SCHEDULE
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."EMPLOYEE_SCHEDULE" ADD CONSTRAINT "SYS_C008222" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EMPLOYEE_SCHEDULE
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."EMPLOYEE_SCHEDULE" ADD CONSTRAINT "SYS_C008221" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table OPERATION
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."OPERATION" ADD CONSTRAINT "OPERATIONS_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table OPERATION
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."OPERATION" ADD CONSTRAINT "SYS_C007963" CHECK ("OPERATION_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PATIENTS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENTS" ADD CONSTRAINT "PK_PATIENTS" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table PATIENT_OPERATION
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_OPERATION" ADD CONSTRAINT "PK_PATIENT_OPERATION" PRIMARY KEY ("OPERATION_NO");

-- ----------------------------
-- Checks structure for table PATIENT_OPERATION
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_OPERATION" ADD CONSTRAINT "SYS_C008249" CHECK ("OPERATION_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table PATIENT_OPERATION
-- ----------------------------
CREATE TRIGGER "C##HOSPITAL_MANAGEMENT_DB"."ADD_BILL_AFTER_OPERATION_INSERTION" AFTER INSERT ON "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_OPERATION" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE
	V_BILL_TYPE VARCHAR2(50);
	V_BILL_CREATE_DATE VARCHAR2(50);
	V_BILL_STATUS VARCHAR2(50);
	V_PATIENT_ID VARCHAR2(50);
	V_AMOUNT NUMBER;
BEGIN
	V_BILL_TYPE:='OPERATION';
	V_BILL_CREATE_DATE:=TO_CHAR( SYSDATE, 'YYYY-MM-DD' );
	V_BILL_STATUS:='DUE';
	V_PATIENT_ID:=:NEW.PATIENT_ID;
	SELECT COST INTO V_AMOUNT 
	FROM OPERATION WHERE ID=:NEW.OPERATION_ID;
	INSERT INTO BILL(BILL_TYPE,BILL_CREATE_DATE,BILL_STATUS,
	PATIENT_ID,AMOUNT) VALUES(V_BILL_TYPE,V_BILL_CREATE_DATE,
	V_BILL_STATUS,V_PATIENT_ID,V_AMOUNT);
END;
/

-- ----------------------------
-- Primary Key structure for table PATIENT_TEST
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_TEST" ADD CONSTRAINT "PK_PATIENT_TEST" PRIMARY KEY ("SAMPLE_NO");

-- ----------------------------
-- Checks structure for table PATIENT_TEST
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_TEST" ADD CONSTRAINT "SYS_C008245" CHECK ("SAMPLE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table PATIENT_TEST
-- ----------------------------
CREATE TRIGGER "C##HOSPITAL_MANAGEMENT_DB"."ADD_BILL_AFTER_TEST_INSERTION" AFTER INSERT ON "C##HOSPITAL_MANAGEMENT_DB"."PATIENT_TEST" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE
	V_BILL_TYPE VARCHAR2(50);
	V_BILL_CREATE_DATE VARCHAR2(50);
	V_BILL_STATUS VARCHAR2(50);
	V_PATIENT_ID VARCHAR2(50);
	V_AMOUNT NUMBER;
BEGIN
	V_BILL_TYPE:='TEST';
	V_BILL_CREATE_DATE:=TO_CHAR( SYSDATE, 'YYYY-MM-DD' );
	V_BILL_STATUS:='DUE';
	V_PATIENT_ID:=:NEW.PATIENT_ID;
	SELECT COST INTO V_AMOUNT 
	FROM TEST WHERE ID=:NEW.TEST_ID;
	INSERT INTO BILL(BILL_TYPE,BILL_CREATE_DATE,BILL_STATUS,
	PATIENT_ID,AMOUNT) VALUES(V_BILL_TYPE,V_BILL_CREATE_DATE,
	V_BILL_STATUS,V_PATIENT_ID,V_AMOUNT);
END;
/

-- ----------------------------
-- Primary Key structure for table PRESCRIPTION
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION" ADD CONSTRAINT "PK_PRESCRIPTION" PRIMARY KEY ("APPOINTMENT_ID");

-- ----------------------------
-- Primary Key structure for table RECEPTIONIST
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."RECEPTIONIST" ADD CONSTRAINT "PK_RECEPTIONIST" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table TECHNICIANS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."TECHNICIANS" ADD CONSTRAINT "TECHNITIANS_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table TEST
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."TEST" ADD CONSTRAINT "TEST_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TEST
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."TEST" ADD CONSTRAINT "SYS_C008261" CHECK ("TEST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERS" ADD CONSTRAINT "SYS_C007914" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERS" ADD CONSTRAINT "SYS_C007915" CHECK ("USER_TYPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERTYPE
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" ADD CONSTRAINT "USERTYPE_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table USERTYPE
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" ADD CONSTRAINT "SYS_C007912" CHECK ("TYPENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table WARD
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."WARD" ADD CONSTRAINT "WARD_PK" PRIMARY KEY ("WARD_NO");

-- ----------------------------
-- Foreign Keys structure for table DOCTORS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."DOCTORS" ADD CONSTRAINT "DOCTORS_FK1" FOREIGN KEY ("ID") REFERENCES "C##HOSPITAL_MANAGEMENT_DB"."USERS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PATIENTS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."PATIENTS" ADD CONSTRAINT "FK1_PATIENTS" FOREIGN KEY ("ID") REFERENCES "C##HOSPITAL_MANAGEMENT_DB"."USERS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PRESCRIPTION
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."PRESCRIPTION" ADD CONSTRAINT "FK1_PRESCRIPTION" FOREIGN KEY ("APPOINTMENT_ID") REFERENCES "C##HOSPITAL_MANAGEMENT_DB"."APPOINTMENTS" ("APPOINTMENT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table RECEPTIONIST
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."RECEPTIONIST" ADD CONSTRAINT "FK_RECEPTIONIST" FOREIGN KEY ("ID") REFERENCES "C##HOSPITAL_MANAGEMENT_DB"."USERS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table TECHNICIANS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."TECHNICIANS" ADD CONSTRAINT "TECHNITIANS_FK" FOREIGN KEY ("ID") REFERENCES "C##HOSPITAL_MANAGEMENT_DB"."USERS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table TEST
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."TEST" ADD CONSTRAINT "FK1_TEST" FOREIGN KEY ("TECHNITIAN_ID") REFERENCES "C##HOSPITAL_MANAGEMENT_DB"."TECHNICIANS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table USERS
-- ----------------------------
ALTER TABLE "C##HOSPITAL_MANAGEMENT_DB"."USERS" ADD CONSTRAINT "USERS_FK" FOREIGN KEY ("USER_TYPE_ID") REFERENCES "C##HOSPITAL_MANAGEMENT_DB"."USERTYPE" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
